apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
spec:
  backend:
    serviceName: master-status
    servicePort: status
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: ingress-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: http
  - port: 443
    protocol: TCP
    targetPort: 443
    name: https
  externalIPs:
  - 192.168.1.187
  selector:
    app: ingress-nginx
