apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
spec:
  rules:
  - host: builds.clementine-player.org
    http:
      paths:
      - backend:
          serviceName: builds
          servicePort: http
  - host: buildbot.clementine-player.org
    http:
      paths:
      - backend:
          serviceName: master-status
          servicePort: status
  - host: clang.clementine-player.org
    http:
      paths:
      - backend:
          serviceName: clang-in-the-cloud
          servicePort: main
# Default backend
  backend:
    serviceName: master-status
    servicePort: status
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: ingress-nginx
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 32145
    protocol: TCP
    targetPort: 80
    name: http
  selector:
    app: ingress-nginx
