apiVersion: v1
kind: ServiceAccount
metadata:
  name: john
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: david
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: john
  namespace: kube-system
- kind: ServiceAccount
  name: david
  namespace: kube-system
